### ISSUE TITLE
Create a plugin to show the status of a cluster

### ISSUE THREAD

**Issue by SamoKopecky** [operate-first/service-catalog#102]
### Additional context

Now that we have all managed operate-first clusters connected to backstage, we should create plugin to show the status of clusters.

Possible approaches:
1. Create a separate status page for all clusters
2. Create a plugin that shows the cluster status in the entity page for a cluster resource

### Acceptance Criteria

- [x] Investigate which solution to implement
- [x] Create a plugin for the backend to query ACM (#106)
- [x] Create a single page to show all of the clusters and their status (#111)
- [x] Create a component that displays detailed information for a cluster resource (#157)
- [x] Update documentation (#147)
- [x] Add more cluster resources to the service catalog (https://github.com/operate-first/apps/pull/2507)
- [x] Update the `backstage API` to include backend plugin endpoints (https://github.com/operate-first/apps/pull/2548, https://github.com/operate-first/apps/pull/2571)
- [x] Better error handling in backend and frontend (#156, #162)
- [x] Refractoring (#161, #163, #168)

### Relevant links

- Creating a plugin: https://backstage.io/docs/plugins/create-a-plugin

**Comment by durandom** [comment]
Cant we show a cluster like any other resource on the frontpage?

**Comment by SamoKopecky** [comment]
Yea that could work too, I'll edit the issue description.

**Comment by SamoKopecky** [comment]
We've decided to implement booth of the approaches, that is to implement an all cluster monitor and a status component for a resource with `kind: cluster`.

**Comment by SamoKopecky** [comment]
We will be using ACM to query the status data of clusters, [this api call](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/apis/apis#description_3) provides these usefull values:
* Number of allocatable and avaliable capacity of
  * CPU cores 
  * Storage size in bytes
  * Number of 1Gi and 2Mi memory pages
  * Memory size
  * Pods
* Cluster detials
  * OpenShift and Kubernetes cluster id
  * Openshift and Kubernetes version
  * Platform (such as OpenStack, BareMetal)
  * Console URL
  * Controler Plane Topology
  * Region
* Conditions
  * Is a cluster avaliable (ManagedClusterConditionAvailable)

We will chose the ones that make sense to show.

**Comment by tumido** [comment]
@SamoKopecky can you provide a API call response example in here?

Correction to the comment above. The entity in service catalog remains `kind: Resource`, for a cluster it must have `.spec.type: cluster`.

**Comment by SamoKopecky** [comment]
> @SamoKopecky can you provide a API call response example in here?
> 
> Correction to the comment above. The entity in service catalog remains `kind: Resource`, for a cluster it must have `.spec.type: cluster`. This will be matched against cluster name in `app-config.prod.yaml`.

That is true, sorry about that I'll edit the comment so that it makes sense.

**Comment by tumido** [comment]
Sample data:
```yaml
apiVersion: clusterview.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ...
    open-cluster-management/created-via: other
  creationTimestamp: ...
  finalizers: ...
  generation: 10
  labels:
    authdeployment: primary
    cloud: Other
    cluster.open-cluster-management.io/clusterset: default
    clusterID: 91976abd-8b8e-47b9-82d3-e84793396ed7
    feature.open-cluster-management.io/addon-application-manager: available
    feature.open-cluster-management.io/addon-cert-policy-controller: available
    feature.open-cluster-management.io/addon-config-policy-controller: available
    feature.open-cluster-management.io/addon-governance-policy-framework: available
    feature.open-cluster-management.io/addon-iam-policy-controller: available
    feature.open-cluster-management.io/addon-work-manager: available
    installer.name: multiclusterhub
    installer.namespace: acm
    local-cluster: "true"
    name: local-cluster
    openshiftVersion: 4.10.26
    velero.io/exclude-from-backup: "true"
    vendor: OpenShift
  managedFields: ...
  name: local-cluster
  resourceVersion: ...
  uid: aada0206-7d43-4383-ab7f-fba9de65a3ad
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  managedClusterClientConfigs:
  - caBundle: <BASE64 encoded CA bundle>
    url: https://api.moc-infra.massopen.cloud:6443
status:
  allocatable:
    cpu: 94500m
    devices.kubevirt.io/kvm: "0"
    devices.kubevirt.io/tun: "0"
    devices.kubevirt.io/vhost-net: "0"
    ephemeral-storage: "1617076575219"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 524485752Ki
    ovs-cni.network.kubevirt.io/br-ex: 3k
    ovs-cni.network.kubevirt.io/br-int: 3k
    ovs-cni.network.kubevirt.io/br-local: 3k
    pods: "750"
  capacity:
    core_worker: "96"
    cpu: "96"
    devices.kubevirt.io/kvm: "0"
    devices.kubevirt.io/tun: "0"
    devices.kubevirt.io/vhost-net: "0"
    ephemeral-storage: 1713516Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 527938680Ki
    ovs-cni.network.kubevirt.io/br-ex: 3k
    ovs-cni.network.kubevirt.io/br-int: 3k
    ovs-cni.network.kubevirt.io/br-local: 3k
    pods: "750"
    socket_worker: "6"
  clusterClaims:
  - name: id.k8s.io
    value: local-cluster
  - name: kubeversion.open-cluster-management.io
    value: v1.23.5+012e945
  - name: platform.open-cluster-management.io
    value: BareMetal
  - name: product.open-cluster-management.io
    value: OpenShift
  - name: consoleurl.cluster.open-cluster-management.io
    value: https://console-openshift-console.apps.moc-infra.massopen.cloud
  - name: controlplanetopology.openshift.io
    value: HighlyAvailable
  - name: id.openshift.io
    value: 91976abd-8b8e-47b9-82d3-e84793396ed7
  - name: infrastructure.openshift.io
    value: '{"infraName":"moc-infra-prdlg"}'
  - name: oauthredirecturis.openshift.io
    value: https://oauth-openshift.apps.moc-infra.massopen.cloud/oauth/token/implicit
  - name: version.openshift.io
    value: 4.10.26
  conditions:
  - lastTransitionTime: "2021-02-20T15:40:10Z"
    message: Accepted by hub cluster admin
    reason: HubClusterAdminAccepted
    status: "True"
    type: HubAcceptedManagedCluster
  - lastTransitionTime: "2021-02-20T15:40:31Z"
    message: Managed cluster joined
    reason: ManagedClusterJoined
    status: "True"
    type: ManagedClusterJoined
  - lastTransitionTime: "2022-08-23T19:46:43Z"
    message: Managed cluster is available
    reason: ManagedClusterAvailable
    status: "True"
    type: ManagedClusterConditionAvailable
  - lastTransitionTime: "2022-08-25T13:31:07Z"
    message: Import succeeded
    reason: ManagedClusterImported
    status: "True"
    type: ManagedClusterImportSucceeded
  version:
    kubernetes: v1.23.5+012e945
```

**Comment by SamoKopecky** [comment]
The basic version of the plugin is created, more issues like #180, #179 and others improve on the plugin in separate issues.
